# --------------------------------------------------------
# Builder
# --------------------------------------------------------

# Use the latest rust image
FROM rust:1.76.0

WORKDIR /app

# Build files
COPY . .

# Move scripts into WORKDIR for convenience
COPY ./scripts .

# Build the BlobstreamX operator
RUN cargo build --bin local_relay --release

# --------------------------------------------------------
# Runner
# --------------------------------------------------------

ENTRYPOINT ["bash", "run_relayer.sh"]
