# --------------------------------------------------------
# Builder
# --------------------------------------------------------

# Use the latest rust image
FROM rust:1.76.0

WORKDIR /app

# Build files
COPY . .

# Build the BlobstreamX operator
RUN cargo build --bin local_relay --release

# --------------------------------------------------------
# Runner
# --------------------------------------------------------

ENTRYPOINT ["cargo", "run", "--bin", "local_relay", "--release"]
