# --------------------------------------------------------
# Builder
# --------------------------------------------------------

# Use the latest rust image
FROM rust:1.76.0

WORKDIR /app

# Build files
COPY . .

# Build the BlobstreamX operator
RUN cargo build --bin blobstreamx --release

# --------------------------------------------------------
# Runner
# --------------------------------------------------------

ENTRYPOINT ["cargo", "run", "--bin", "blobstreamx", "--release"]
