[profile.default]
solc = '0.8.22'
src = "src"
out = "out"
libs = ["lib"]

[fmt]
line_length = 100
tab_width = 4
func_attrs_with_params_multiline = true
ignore = ["lib/**"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
